controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 1000
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    joints:
      # Front right leg
      - front_right_shoulder_joint
      - front_right_elbow_joint
      - front_right_wrist_joint
      # Front right leg
      - front_left_shoulder_joint
      - front_left_elbow_joint
      - front_left_wrist_joint
      # Back right leg
      - back_right_shoulder_joint
      - back_right_elbow_joint
      - back_right_wrist_joint
      # Back right leg
      - back_left_shoulder_joint
      - back_left_elbow_joint
      - back_left_wrist_joint

joint_group_position_controller:
  ros__parameters:
    joints:
      # Front right leg
      - front_right_shoulder_joint
      - front_right_elbow_joint
      - front_right_wrist_joint
      # Front right leg
      - front_left_shoulder_joint
      - front_left_elbow_joint
      - front_left_wrist_joint
      # Back right leg
      - back_right_shoulder_joint
      - back_right_elbow_joint
      - back_right_wrist_joint
      # Back right leg
      - back_left_shoulder_joint
      - back_left_elbow_joint
      - back_left_wrist_joint
    command_interfaces:
      - position 
    state_interfaces:
      - position